### ISSUE TITLE
Slides for IETF 117

### ISSUE THREAD

**Issue by danielkinguk** [danielkinguk/tvr-requirements#3]
Draft slides for IETF 117. 
[draft_kcs_tvr_requirements_ietf117_v1.pptx](https://github.com/danielkinguk/tvr-requirements/files/12098318/draft_kcs_tvr_requirements_ietf117_v1.pptx)

**Comment by BrianSipos** [comment]
The slides look good, I will touch up a little bit and can attach a new draft before Friday.

**Comment by BrianSipos** [comment]
My updates flatten out some of the third-level list items and add discussion about examples, but leave the structure in place otherwise.
[draft_kcs_tvr_requirements_ietf117_v2.pptx](https://github.com/danielkinguk/tvr-requirements/files/12113881/draft_kcs_tvr_requirements_ietf117_v2.pptx)
