### ISSUE TITLE
Changes to Topology and Node

### ISSUE THREAD

**Issue by danielkinguk** [danielkinguk/tvr-requirements#31]
Comment from IETF 118:

JW: change of entity properties may need topology change, can discuss in
future.
great way to attack the network

**Comment by luismcontreras** [comment]
Note that teh charter states: "Time-based changes may include changes to links, adjacencies, cost, and - in some cases - traffic volumes." 

Curren text in section 3.3.3 states the following: "Schedules on a link SHALL be used
   to indicate the validity of the entire link or changing properties of
   that entity."

Thus I think we already cover this as requirement. I propose to close this issue.

**Comment by danielkinguk** [comment]
Agree. Also removed conformance language in latest version.
