### ISSUE TITLE
Changes on LAG should be considered as part of TVR scope?

### ISSUE THREAD

**Issue by luismcontreras** [danielkinguk/tvr-requirements#34]
When thinking on the issue open for the properties of the links, this point about link-aggregation came to my mind.

Should any predictable change on link aggregation be considered as case for TVR? Probably not very frequent case, or in other words, a corner case. But just for figuring out an answer to some potential quesiton in the future.

**Comment by BrianSipos** [comment]
If existing aggregation is modeled by a type of termination point which has an 'enabled' state, then this can be captured as a schedule applied to that entity which is coordinated to the state of the other constituent termination points being aggregated.
