### ISSUE TITLE
Discuss intrinsic and extrinsic schedule modeling options

### ISSUE THREAD

**Issue by BrianSipos** [danielkinguk/tvr-requirements#5]
Within the [Resource Scheduling](https://www.ietf.org/archive/id/draft-kcs-tvr-requirements-00.html#name-resource-scheduling) section, there should be a discussion of how a schedule is applied to a data model: either intrinsic to the model parameters or as extrinsic changes to the model.

**Comment by BrianSipos** [comment]
@danielkinguk these changes can be used on their own or combined with any of your edits

**Comment by danielkinguk** [comment]
Cool, thanks Brian. I will continue to work on the new version over the weekend.
