### ISSUE TITLE
Review latest TVR Use Case I-D and check for updates for Requirements I-D

### ISSUE THREAD

**Issue by danielkinguk** [danielkinguk/tvr-requirements#8]
https://datatracker.ietf.org/doc/html/draft-ietf-tvr-use-cases-02

**Comment by luismcontreras** [comment]
New version -03 is available. Section 6 describes problems to solve. I will check if there is something new in terms of requirements, targeting 20:00 CET for this.

**Comment by danielkinguk** [comment]
Going to leave this open. We can discuss new requirements in the WG slides/discussion, or even prepare a new version of the I-D and submit when the Submission Tool opens again at the start of IETF week.
